# Site settings
title: Yonah Aviv
description: Smooth Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://y330.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yonah Aviv
user_description: I am a post-secondary student, and also a relatively experienced computer programmer. I am experienced in Python and in the front-end, but I learn new things everyday.
user_title: Student
email: avivyonah@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
