# Site settings
title: Yonah Aviv
description: Responsive Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://y330.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yonah Aviv
user_description: Unqualified yet experienced computer programmer.
user_title: Student
email: avivyonah@gmail.com
# twitter_username: lorem_ipsum
github_username:  y330
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
